export const cardData= [

    {  
      index: 0,
      img: "./public/card/1.png",
      title: 'Apple Watch',
      series: 'Series 5 SE',
      price: '529.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
      description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 1,
      img: "./public/card/2.png",
      title: 'Sony ZX330BT',
      series: 'Light Grey',
      price: '39.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
      description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 2,
      img: "./public/card/3.png",
      title: 'Iphone 11',
      series: 'Serious Black',
      price: '629.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
      description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 3,
      img: "./public/card/4.png",
      title: 'Iphone 11',
      series: 'Subway Blue',
      price: '629.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
      description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 4,
      img: "./public/card/5.png",
      title: 'Iphone 13 Pro',
      series: 'Silly Silver',
      price: '1529.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
      description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 5,
      img: "./public/card/6.png",
      title: 'Iphone 13 Pro',
      series: 'Grey',
      price: '1529.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
      description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 6,
      img: "./public/card/7.png",
      title: 'Samsung Galaxy Note 21 ',
      series: '2 - Options',
      price: '999.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
     description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
    {
      index: 7,
      img: "./public/card/8.png",
      title: 'Samsung Galaxy S21+',
      series: 'Lilac Purple',
      price: '849.99',
      smv: '$',
      history: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!',
     description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deleniti ex at cumque autem, amet, quas aut illum beatae optio animi, ad ut voluptatibus quo modi alias veniam. Repellat, commodi rerum!'
    },
  ];
